name: listing, testing, and running code
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo systemctl start docker
      
      - name: Install dependencies
        run: npm install
      - name: Build code
        run: npm run build:prod
      - name: Lint code
        run: npm run lint:ts
      - name: Lint scss
        run: npm run stylelint:ts
      - name: Test code
        run: npm run test:unit
      - name: Build Storybook
        run: npm run storybook:build
      - name: Test Screenshots
        run: npm run test:ui:ci
